### ISSUE TITLE
Combine the networks sections (discovery , access, mapping) into one section

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#126]
It may make sense to create a narrative link between discovery, access and mapping (plus vulnerability analysis), as that will underscore the overall point of this exercise – otherwise often some of these elements may appear as l'art pour l'art – it also helps to evaluate how much time is needed altogether, in order to prioritise when necessary (e.g. focus on mapping when there is no full five days)

**Comment by joncamfield** [comment]
The main culprit here is the network_access component I feel; as it is the biggest time-sink in an audit process. I've re-worked _discovery and _mapping to be relatively independent items, and de-prioritized the _access components.  I considered merging _access into _discovery, but the framing is very different and deserves separate discussion due to the aggressiveness of the exercises and potential for network disruption.  For 1.0 I want to leave them intact (with the above caveats) to match the curricula as developed.  Closing for now, but feel free to re-open and/or re-tag to a different milestone.
